### ISSUE TITLE
node.js에서 flask로

### ISSUE THREAD

**Issue by parkss404** [parkss404/Serp1ck#10]
flask가 파이썬 기반이고, 챗봇 기능을  더 가볍게 만들 수 있기 때문에 flask로 진행하려고 합니다. 다들 어떻게 생각하시나요?

**Comment by kimtaewan22** [comment]
원래 진행하려고 한 언어가 파이썬이고 flask로 챗봇 기능을 더 손 쉽게 만들 수 있기에 flask로 진행하는 것이 좋다고 생각합니다. 또한 관련 라이브러리가 많아서 어렵지 않게 진행할 수 있을 거라는 생각이 듭니다.
