### ISSUE TITLE
groom ide 사용추천

### ISSUE THREAD

**Issue by parkss404** [parkss404/Serp1ck#11]
groom에서 제공하는 개발용 웹이있는데 이걸 사용하면 웹 서버를 직접 만들 필요 없이 공유 ip가 할당되어서 손쉽게 서버를 열 수 있더라구요! 
또한 flask나 node.js같은 프레임워크들을 따로 컴퓨터에 설치할 필요가 없고 groom 서버에 이미 깔려있어서 바로 쓸 수 있어요. 한번 써보시는 것이 좋을 것 같습니다.

https://ide.goorm.io/

**Comment by kimtaewan22** [comment]
groom ide가 무료로 사용할 수 있고 파이썬이나 다른 언어들도 groom ide를 이용해서 따로 메모리를 사용할 필요 없이 groom ide 자체에서 제공해주는 공간에서 작업을 하니 편한 것 같습니다.
