### ISSUE TITLE
챗봇개발을 쉽게 하도록 도움을 주는 dialogflow

### ISSUE THREAD

**Issue by parkss404** [parkss404/Serp1ck#12]
카카오 오픈빌더에서 제공하는 챗봇 개발기능도 좋지만 dialogflow를 이용하면 더 활용성이 좋을 것 같은데 어떻게 생각하시나요?

**Comment by kimtaewan22** [comment]
dialogflow를 사용하면 비코딩 방식으로 대화-흐름의 형태로 만들기만 하면 챗봇을 만들 수 있다는 용이성이 있습니다. 그래서 챗봇 개발기능 대신 dialogflow를 사용하는 것도 좋다고 생각합니다.
