### ISSUE TITLE
음식 질문 선정

### ISSUE THREAD

**Issue by KGE108** [parkss404/Serp1ck#13]
음식 질문을 매운음식/안매운 음식, 혼밥 유무, 고기의 메인여부로 결정할까 하는데 어떻게 생각하시나요?

**Comment by kimtaewan22** [comment]
첫 번째 질문이 맵기의 유무이고 두 번째 질문이 혼밥 유무 이런식으로 순차적으로 질문을 받는 건가요?

**Comment by KGE108** [comment]
맞습니다. 우선 대학생들을 대상으로 하는 서비스이기 때문에 혼밥 여부를 먼저 파악하고 가장 크게 갈리는 맵기의 정도와 고기가 메인인지 아닌지 순차적으로 질문을 받는 것이 좋을 것 같습니다.

**Comment by kimtaewan22** [comment]
그렇다면 혼밥 여부에 따라서 메뉴 자체가 바뀔 수도 있다는 거네요?

**Comment by KGE108** [comment]
맞습니다. 혼밥이 가능한 메뉴가 있고 불가능한 메뉴가 있기 때문에 그 메뉴를 먼저 골라내는 것이 어떨지 생각했습니다.
