### ISSUE TITLE
dialogflow 오류 

### ISSUE THREAD

**Issue by parkss404** [parkss404/Serp1ck#16]
dialogflow에서 json파일을 원래 수정해서 다시 import해서 챗봇으로 쓸 수 있었는데 지금 그 기능이 막힌 것 같아요.. 방법이 없을까요?

**Comment by kimtaewan22** [comment]
JSON형식의 파일을 import 할 때 오류가 발생하는 건가요?

**Comment by kimtaewan22** [comment]
알아보니 dialogflow는 현재 업데이트 된 이후로 해당 기능이 막혀서 이용할 수 없을 거 같습니다.

**Comment by parkss404** [comment]
알겠습니다.카카오 오픈빌더를 이용하는 방법밖에 없겠군요
