### ISSUE TITLE
flask서버 카카오톡과 연결 실패 오류  

### ISSUE THREAD

**Issue by parkss404** [parkss404/Serp1ck#17]
groom ide에서 제공하는  flask url로 카카오 챗봇에 연동했는데 오류가 뜨네요

**Comment by kimtaewan22** [comment]
어떤 식으로 오류가 발생하나요?

**Comment by parkss404** [comment]
ide를 이용하다가 포트 포워딩이 잘못되어서 서버연결이 안되었던 것 이었습니다. 해결했습니다.
