### ISSUE TITLE
데이터 크롤링

### ISSUE THREAD

**Issue by kimtaewan22** [parkss404/Serp1ck#18]
현재 파이썬으로 데이터를 크롤링 해올 때 거리 순서, 리뷰 순서, 최소 주문 금액 순 등 여러 기준으로 음식점들을 크롤링 해올 수 있도록 했는데 더 필요하거나 추가해야 될 기능이 있을까요?

**Comment by parkss404** [comment]
별점순도 가져올 수 있을까요?

**Comment by parkss404** [comment]
그 정도로 분류하면 충분할 것 같아요!

**Comment by kimtaewan22** [comment]
그러면 최종적으로 위 기능 구현을 마무리하겠습니다.
