### ISSUE TITLE
맛집 추천

### ISSUE THREAD

**Issue by kimtaewan22** [parkss404/Serp1ck#19]
추천 맛집으로 현재 설문조사를 통해 얻은 데이터와 요기요를 크롤링해서 별점이 높고 리뷰수가 많은 식당과 주변에서 전해들은 식당을 종합해서 정하려고 하는데 어떻게 생각하시나요?

**Comment by KGE108** [comment]
좋을 것 같습니다. 요기요는 많은 사람들이 이용하는 어플이니 괜찮을 것 같습니다.

**Comment by parkss404** [comment]
종합을 해서 하나의 음식에 하나의 값을 출력하는 걸로 할까요?

**Comment by KGE108** [comment]
나쁘지 않을 것 같습니다. 가장 평이 좋은 음식점을 보여주는거 어떨까요?
