### ISSUE TITLE
excel file column 

### ISSUE THREAD

**Issue by kimtaewan22** [parkss404/Serp1ck#2]
The size of the first column should be adjusted so that all the store names are visible

**Comment by parkss404** [comment]
from openpyxl.utils import get_column_letter
모듈에 엑셀정보를 수정할 수 있는 기능이 있을 것 같습니다.

**Comment by kimtaewan22** [comment]
모듈을 확인해보니 get_column_letter 의 기능을 사용해서excel_sheet.column_dimensions[get_column_letter(1)].width=40 코드를 넣고 프로그램을 실행하니까 엑셀파일의 가게이름 부분 열의 너비가 잘 조절 됐습니다
