### ISSUE TITLE
맛집 리스트 정리

### ISSUE THREAD

**Issue by kimtaewan22** [parkss404/Serp1ck#21]
![KakaoTalk_20220601_152745634](https://user-images.githubusercontent.com/85469656/171343402-85798b65-638f-41ea-8af1-f979a29ae543.jpg)

최종적으로 위 분류 기준대로 해당 음식에 대한 맛집을 리스트로 정리하려고 하는데 더 필요하거나 고려해야할 사항이 있을까요?

**Comment by parkss404** [comment]
네 저희 맛집리스트랑 연결시키면 될 것같습니다.

**Comment by kimtaewan22** [comment]
그러면 구글 설문조사를 통해서 얻은 데이터와 주위에서 추천 받은 맛집리스트랑 연결해서 마무리하겠습니다.
