### ISSUE TITLE
에브리타임 설문진행

### ISSUE THREAD

**Issue by parkss404** [parkss404/Serp1ck#22]
![KakaoTalk_Photo_2022-06-01-15-52-28](https://user-images.githubusercontent.com/81512557/171345172-95a3b2ba-c718-4fbb-80c1-84192a908e0a.png)
에브리타임 설문 이렇게 진행했습니다!

**Comment by KGE108** [comment]
좋습니다! 구글폼 설문조사 결과 엑셀 링크는 여기 있습니다!
https://docs.google.com/spreadsheets/d/1paDe1HkGuWvJqUaJGnQNgNjrFuglGvk5SdyUCKfHkDw/edit?usp=sharing

**Comment by kimtaewan22** [comment]
해당 설문 조사 결과와 크롤링 결과를 토대로 맛집 리스트를 만들었습니다!
