### ISSUE TITLE
맛집 정보

### ISSUE THREAD

**Issue by kimtaewan22** [parkss404/Serp1ck#23]
현재 dataSorting 파일에 음식과 위치 정보에 따른 맛집 리스트가 올라가 있는데 음식과 위치에 맞게 맛집 리스트 False 부분을 채워주면 될 거 같습니다!

**Comment by parkss404** [comment]
False부분 채워주시면 다시 챗봇 리스트를 변경하도록 하겠습니다.

**Comment by KGE108** [comment]
false 부분 제가 채워두겠습니다.
