### ISSUE TITLE
챗봇 UI

### ISSUE THREAD

**Issue by kimtaewan22** [parkss404/Serp1ck#24]
현재 챗봇은 뭐먹지 라는 키워드를 입력해야 음식을 추천해주는 방식인데, 챗봇에 들어가면 챗봇에 대한 설명과 음식을 추천받을 것인지 선택할 수 있도록 안내문구를 띄우는 형태로 바꾸는 건 어떨까요?

**Comment by parkss404** [comment]
네 카카오 오픈빌더에서 웰컴블록을 변경시키면 될 것 같네요
