### ISSUE TITLE
챗봇에서 api를 이용할때 속도가 느림

### ISSUE THREAD

**Issue by parkss404** [parkss404/Serp1ck#25]
아무래도 서버를 열어서 데이터를 주고 받다보니 채팅 속도가 느려집니다. 그래서 음식추천과 식당추천 중에서 음식추천은 api기능을 사용 안하고 카카오 오픈빌더 내에서 제공하는 기능을 활용하는 것은 어떨까요?

**Comment by kimtaewan22** [comment]
확실히 현재 서버를 열어서 하는 방식으로 하다보니 채팅 속도가 많이 느린 것이 느껴졌습니다. 말씀하신대로 카카오 오픈빌더에서 제공하는 기능을 활용하는 것이 좋은 방안이라고 생각합니다.

**Comment by parkss404** [comment]
오픈빌더의 컨텍스트 기능을 한번 이용해 봐야겠군요
