### ISSUE TITLE
음식점 리스트 URL정보 추가

### ISSUE THREAD

**Issue by parkss404** [parkss404/Serp1ck#26]
챗봇에서 사용하는 음식점 리스트에 URL기능을 추가해서 사용자들이 추천받은 음식점에 대한 자세한 정보를 링크를 타고 바로 열람할 수 있도록 하면 어떨까요?

**Comment by kimtaewan22** [comment]
음식점 리스트에 URL을 추가해서 사용자들이 해당 음식점에 대해 조금 더 자세한 정보를 알 수 있도록 하는 것도 좋은 방법이라고 생각합니다. 해당 음식점에 대한 링크는 따로 정리해서 올리도록 하겠습니다.
