### ISSUE TITLE
이진수 표기법을 사용한 음식 리스트

### ISSUE THREAD

**Issue by parkss404** [parkss404/Serp1ck#28]
질문의 개수는 총 3개입니다. 
각 질문은 예,아니오 두 가지의 답변을 받을 수 있으며 저는 각 답변을 1과 0으로 Q1,Q2,Q3 변수에 저장할 것입니다. 
그리고 keynum변수에 Q1 * 100 + Q2 * 10 + Q3 값을 집어넣으면
최종적으로 3개의 질문이 끝났을 때 101,110,011 과 같은 값을 얻을 수 있습니다.
그리고 keynum의 이진수를 10진수로 변환하게 되면 0-7까지 각각의 고유한 값을 얻어낼 수 있음으로
0-7까지 존재하는 음식리스트의 인덱스 값에 keynum을 넣어서 사용자에게 적절한 음식을 추천해줍니다.

Ex) 음식리스트[7] = 치킨 
       음식리스트[0] = 삼겹살

**Comment by kimtaewan22** [comment]
이전에 같이 토의하면서 생각해낸 방법이네요 음식리스트의 고유의 값을 정하는데 좋다고 생각합니다.

**Comment by parkss404** [comment]
코드를 치면서 느낀점인데 굳이 Q1 * 100 + Q2 * 10 + Q3 이런식으로 표현할 필요없이 
Q1 * 4 + Q2 * 2 + Q3 이렇게 keynum에 넣으면 이진수 변환을 추후에 하지 않아도 되겠네요
