### ISSUE TITLE
챗봇 음식점 추천

### ISSUE THREAD

**Issue by kimtaewan22** [parkss404/Serp1ck#29]
음식점을 추천이 완료되었을 때 해당 옵션으로 음식점의 위치와 URL을 필요하면 받을 수 있도록 하는 것은 어떨까요?

**Comment by parkss404** [comment]
좋습니다. 다만 위치정보와 url정보가 있어야 겠군요!

**Comment by KGE108** [comment]
음식점의 주소가 있다면 위치를 불러올 수 있나요?

**Comment by kimtaewan22** [comment]
네 네이버 지도에서 음식점 URL을 가져와서 전달하는 방식으로 하면 될 것 같습니다
