### ISSUE TITLE
맛집 서비스를 어떤 툴들을 이용해 만들 것인가

### ISSUE THREAD

**Issue by parkss404** [parkss404/Serp1ck#3]
크롤링을 이용하여 정보 수집을 하고, 수집한 정보의 전달을 웹으로 할지 앱으로 할지 등에 대한 논의가 필요하다.

**Comment by kimtaewan22** [comment]
크롤링을 이용하여 얻은 데이터를 엑셀 파일로 저장한 다음에 이것을 데이터베이스에 전달하는 게 좋을 거 같다.

**Comment by parkss404** [comment]
웹은 접근성 측면에서 간단히 가벼운 음식등을 추천하기에 적절하지 못한 것 같습니다.

**Comment by parkss404** [comment]
웹은 접근성 측면에서 간단히 가벼운 음식등을 추천하기에 적절하지 못한 것 같습니다.

**Comment by parkss404** [comment]
그래서 그런데 아니면 카카오 챗봇을 이용하는건 어떨까요 ?

**Comment by kimtaewan22** [comment]
카카오 챗봇을 사용하는 것이 사용자 측면에서 간단하고 좋아보임.

**Comment by parkss404** [comment]
https://luckygg.tistory.com/295?category=930587 
이 링크를 통해서 따라해보면 카카오 챗봇을 노드 js를 이용하여 간단히 작동할 수 있도록 하는데 한번 해보겠습니다.

**Comment by KGE108** [comment]
카카오 챗봇을 이용했을 때 생기는 불편함은 없을까요?
깔끔하게 볼 수 있었으면 좋겠습니다.

**Comment by parkss404** [comment]
단점이라고 한다면 아무래도 챗봇에 원하는 기능을 모두 넣기에는 한계가 있다는 점 같아요. 다만 사용자 반응을 통해 서비스를 개선하기 위해서  사용자들에게 익숙하고 접근성이 좋은 카카오톡을 이용하면 빠르게 반응을 받을 수 있을 것 같아요.

**Comment by KGE108** [comment]
그렇다면 챗봇 이용이 좋을 것 같습니다.
