### ISSUE TITLE
챗봇 음식점 음식 사진

### ISSUE THREAD

**Issue by kimtaewan22** [parkss404/Serp1ck#33]
음식추천을 다 받고 음식점까지 결정이 되었을 때 음식점 이름과 함께 해당 음식점 음식을 사진으로 같이 보여준다면 좋을 거 같은데 어떻게 생각하시나요?

**Comment by kimtaewan22** [comment]
해당 이미지에 대한 URL을 가져와 챗봇에서 연결할 생각입니다.

**Comment by parkss404** [comment]
네 좋습니다!
