### ISSUE TITLE
챗봇 위치데이터 지도

### ISSUE THREAD

**Issue by kimtaewan22** [parkss404/Serp1ck#35]
음식을 추천 받은 뒤에 정문,중문,서문,후문 등 위치데이터를 받는데 이때 이 위치가 정확히 어딘지 모르는 사용자들을 위해서 학교 지도를 같이 띄어주면 좋을 거 같습니다

**Comment by parkss404** [comment]
학교 지도 정보 이미지는 어디서 가져올까요?

**Comment by kimtaewan22** [comment]
네이버 지도를 통해 가져와서 위치를 직접 체크하려고 합니다.
