### ISSUE TITLE
추천 음식 질문 정하기

### ISSUE THREAD

**Issue by KGE108** [parkss404/Serp1ck#4]
추천 음식을 어떤 기준으로 나눠서 질문할까요?

**Comment by kimtaewan22** [comment]
맵기, 면 유무 등의 기준이 있으면 좋을 거 같아

**Comment by parkss404** [comment]
모든 음식의 종류를 담을 수 없으니 일반적으로 가장 선호되는 음식을 구글링을 통해 모으고, 최대한 음식 갯수를 줄여 그에 맞게 질문의 갯수를 정해야 할 것 같습니다.  
예를 들어 챗봇에서의 질문에 대한 답은 O,X로 진행될 것이기에 2의 n제곱의 음식 수가 있을 때 n개의 질문이 나올 수 있을 것입니다.

**Comment by KGE108** [comment]
그렇다면 3가지 정도의 질문은 어떨까요? 많은 질문은 사용자가 번거로울 수 있다고 생각합니다.

**Comment by parkss404** [comment]
좋은 것 같네요. 아마 3가지 질문으로는 1대1로 맞춤 음식을 추천해주긴 힘들겠죠. 8가지의 경우의 수에서 각 경우당 여러 음식이 될 텐데 그러면 최종적으로 음식 선택은 사용자가 하도록 합시다. 생각해 보면 1대1로 너무 확실하게 정해버렸을 때 그 음식이 취향에 맞지 않을 때 오히려 사용자에게 큰 반감이 들지도 모르니 그렇게 하는게 좋을 것 같아요.

**Comment by KGE108** [comment]
사용자가 선택하기엔 그것도 고민해야 할텐데 랜덤 추천은 어떤가요?

**Comment by KGE108** [comment]
음식 종류는 30가지 정도로 추려서 8개의 그룹으로 나누고 랜덤으로 뽑으면 좋을 것 같습니다.
