### ISSUE TITLE
기말 발표준비

### ISSUE THREAD

**Issue by parkss404** [parkss404/Serp1ck#41]
저희 기말 발표 준비도 이제 해야할 것 같은데 정리해봅시다!

**Comment by KGE108** [comment]
좋습니다! 구현된 부분과 구현하지 못한 부분을 구별해두면 좋을 것 같습니다

**Comment by kimtaewan22** [comment]
어떤 점에 초점을 맞춰서 구현을 했는지 발표하면 좋을 거 같네요
