### ISSUE TITLE
앱 질문 관련

### ISSUE THREAD

**Issue by KGE108** [parkss404/Serp1ck#42]
OX 발화에 따라서 다음 질문을 다르게 입력하는 방식을 사용해볼 생각입니다.

**Comment by kimtaewan22** [comment]
OX발화에 따라 해당 OX 값을 누적해서 저장하고 해당 누적값에 따라 질문을 다르게 입력하는 방식을 사용하면 될 거 같습니다

**Comment by KGE108** [comment]
값을 누적하는 방법을 찾기 어려워 질문에 따라 페이지 이동을 조절해서 새로운 페이지를 만들었습니다.
