### ISSUE TITLE
카카오 챗봇 시간제한

### ISSUE THREAD

**Issue by parkss404** [parkss404/Serp1ck#43]
사용자 발화 후 5초 이내에 서버와 데이터를 주고 받아야만 작동합니다.
속도를 줄이기 위한 코드 수정이 필요할 것으로 보입니다.

**Comment by kimtaewan22** [comment]
맞습니다 현재 서버와 데이터를 주고받는 시간이 많이 느린 것으로 보입니다.

**Comment by KGE108** [comment]
발화가 늦는다면 사용자들이 불편할 수 있으니 수정하는게 좋을 것 같습니다.
