### ISSUE TITLE
카카오 챗봇 설명

### ISSUE THREAD

**Issue by kimtaewan22** [parkss404/Serp1ck#44]
현재 카카오 챗봇 채널 설명을 1TRY에 맞게 바꿔야 될 거 같습니다.

**Comment by KGE108** [comment]
이름과 한줄소개를 수정할 필요가 있어보이는데, 1try에 당신이 원하는 음식을
이런 식으로 문구를 바꿔도 좋을 것 같습니다.

**Comment by kimtaewan22** [comment]
해당 부분 참고해서 수정하도록 하겠습니다.
