### ISSUE TITLE
속도 저하 이슈 해결방안

### ISSUE THREAD

**Issue by parkss404** [parkss404/Serp1ck#47]
현재 replit에서 서버를 돌리고 있는데 확인해보니 
플랜을 업그레이드를 하면 속도가 4배 빨라진다고 하더라구요. 
지금 구름ide로도 돌려보려고 하는데 만약 여기서도 속도가 느리다면 업그레이드해서
7달러 그냥낼까요? 2달러씩 걷어서?

**Comment by kimtaewan22** [comment]
아마 업그레이드를 하면 훨씬 빨라질 것으로 예상이 됩니다. 현재 업그레이드를 해서 돌려본 결과 빨라진 것으로 확인되었습니다.

**Comment by parkss404** [comment]
replit 유료버전에서 서버 항상 켜두기 기능이 있어서 
컴퓨터를 끈 상태로도 언제든 접속할 수 있군요
