### ISSUE TITLE
챗봇 사용자 피드백

### ISSUE THREAD

**Issue by kimtaewan22** [parkss404/Serp1ck#48]
챗봇을 배포하고 실제로 사용해보도록 한 뒤, 피드백을 받는 것은 어떻게 생각하시나요?

**Comment by parkss404** [comment]
피드백을 바탕으로 개선점을 모색해보는 방안도 좋을 것 같군요

**Comment by KGE108** [comment]
피드백을 통해 추가할 기능들을 받아볼 수도 있을 것 같습니다.

**Comment by kimtaewan22** [comment]
그러면 일요일에 배포를 해보고 사용자를 통해 피드백을 받도록 하겠습니다.
