### ISSUE TITLE
앱에서 챗봇 연결

### ISSUE THREAD

**Issue by KGE108** [parkss404/Serp1ck#49]
앱에서 음식을 결정하고 그 메뉴를 챗봇에 입력해 음식점을 추천받는건 어떨까요?

**Comment by kimtaewan22** [comment]
그렇게 되면 과정을 두 번씩이나 거쳐가는 거라서 일단 앱으로 구현한 것까지만 하는 게 좋을 거 같습니다!

**Comment by KGE108** [comment]
알겠습니다!
