### ISSUE TITLE
크롤링 데이터 가공

### ISSUE THREAD

**Issue by kimtaewan22** [parkss404/Serp1ck#5]
요기요 웹을 이용해서 데이터를 크롤링 해왔을 때 내가 원하지 않는 정보도 같이 있는데 여기서 어떻게 내가 원하는 정보만 가져올 수 있나요?

**Comment by parkss404** [comment]
요기요 웹 내부에서 제공하는 검색 필터링 기능을 잘 이용해야 할 것 같습니다. 
찾아보니 필터링 기능에는 리뷰 순 , 별점 순 , 거리 순 등이 있고 셀레니움을 이용할 때 해당 부분 클래스를 찾아서 입력하도록 하는 건 어떨까요?

**Comment by kimtaewan22** [comment]
해당 필터링 기능을 통해서 자료를 수집한 경우에도 예상치 못 하게 원치 않는 데이터가 섞여 있는 경우가 더러 있습니다. 예를 들어 치킨집을 크롤링 해왔는데, 돈가스 가게가 같이 수집되는 경우입니다.

**Comment by parkss404** [comment]
그러면 일단 대표적인 음식 리스트 중에서는 크롤링 받아온 데이터를 저희가 직접 분류해볼 필요가 있을 것 같습니다.

**Comment by kimtaewan22** [comment]
그러면 해당 데이터를 크롤링 해와서 엑셀데이터로 저장해놓고 거기서 수작업으로 분류하는 것으로 하겠습니다.
