### ISSUE TITLE
readme 파일 수정

### ISSUE THREAD

**Issue by parkss404** [parkss404/Serp1ck#52]
readme 파일 수정 진행하겠습니다. 어떤것들이 더 필요할까요?

**Comment by kimtaewan22** [comment]
챗봇이 어떻게 구현이 되는 지 알려주기 위해서 실제 사용방법을 알려주는 것이 좋아보입니다.

**Comment by parkss404** [comment]
사용방법 및 소개글 작성하겠습니다.
