### ISSUE TITLE
리스트 오류발생

### ISSUE THREAD

**Issue by parkss404** [parkss404/Serp1ck#53]
현재 챗봇에서 이미지리스트, url리스트 , 음식점리스트 세가지의 리스트를 각각 개별적으로 가져오다보니 중간에서 에라가 자꾸 발생하는군요. 
다음에는 데이터베이스를 이용해서 리스트를 조금더 깔끔하게 정리할 필요가 있을 것 같습니다.

**Comment by kimtaewan22** [comment]
맞습니다. 리스트를 하나하나 다 작성해서 작업하는 것도 시간이 오래 걸리고 오류 가능성이 높은 것 같습니다.

**Comment by parkss404** [comment]
나중에 엑셀파일을 가져오는 방법을 모색해봐야겠네요
