### ISSUE TITLE
챗봇 내부 카카오톡 공유기능 

### ISSUE THREAD

**Issue by parkss404** [parkss404/Serp1ck#54]
카카오톡 친구 간 저희 채널을 공유하는 기능을 추가해볼까 합니다! 어떠세요?

**Comment by kimtaewan22** [comment]
공유기능이 추가된다면 사용자들이 조금 더 편리함을 느낄 수 있을 거 같습니다.

**Comment by parkss404** [comment]
넵 그럼 그렇게 진행하겠습니다!
