### ISSUE TITLE
마지막 응답부분 이미지

### ISSUE THREAD

**Issue by parkss404** [parkss404/Serp1ck#55]
마지막 응답부분 이미지에 썸네일로 해당 음식점의 음식을 가져오도록 하는건 어떨까요?

**Comment by kimtaewan22** [comment]
사용자들이 직관적으로 볼 수 있기에 좋은 방법인 거 같습니다.

**Comment by parkss404** [comment]
넵 그럼 그렇게 진행하도록 하겠습니다.!
