### ISSUE TITLE
음식선택부분 수정

### ISSUE THREAD

**Issue by parkss404** [parkss404/Serp1ck#57]
리스트 인덱스를 생각해서 코드를 짜다보니 기존 버튼 클릭형식에서 사용자가 직접 음식 이름을 채팅창에 치는 방식으로 
수정 해볼까합니다. 어떨까요?

**Comment by kimtaewan22** [comment]
해당 음식이 없는 경우 여러 번 입력을 하는 경우가 발생할 수도 있겠네요?

**Comment by KGE108** [comment]
메뉴 이름들을 보여주고 그 중에서 채팅을 적는건 어떨까요?

**Comment by parkss404** [comment]
![KakaoTalk_Photo_2022-06-04-22-25-35](https://user-images.githubusercontent.com/81512557/172001165-121a33ff-b86c-4910-a3ef-e0db62d899a3.jpeg)
이렇게 메뉴이름은 다 보입니다!

**Comment by kimtaewan22** [comment]
기존에 하나의 음식만 추천해주던 거에서 위처럼 바뀐 건가요?
