### ISSUE TITLE
챗봇 안내문

### ISSUE THREAD

**Issue by kimtaewan22** [parkss404/Serp1ck#58]
챗봇과 대화를 시작했을 때 채널에 대한 설명과 챗봇이 맛집을 알려줄 수 있는 음식을 기준을 가지고 제시해주면 좋을 거 같다는 생각이 듭니다. 어떠신가요?

**Comment by parkss404** [comment]
좋습니다. 훨씬 편리하겠네요!

**Comment by kimtaewan22** [comment]
그러면 위처럼 수정하고 나머지 UI는 사용자들로부터 피드백을 받고 추가로 수정하는 걸로 하겠습니다.
