### ISSUE TITLE
위치 데이터 설정

### ISSUE THREAD

**Issue by kimtaewan22** [parkss404/Serp1ck#6]
충북대학교를 중심으로 사람들이 위치를 정할 수 있도록 중문, 정문, 후문 등의 위치에서 중심 건물들을 설정해야 될 거 같다.

**Comment by parkss404** [comment]
배달 음식의 경우에도 반경이 있는 것처럼 사용자 위치 정보를 받아올 수 있는 방법이 있었으면 좋겠네요.

**Comment by KGE108** [comment]
사용자가 구역을 선택할 수 있도록 해 그 인근의 음식점들만 보여준다면 좋을 것 같습니다.

**Comment by kimtaewan22** [comment]
그 인근의 음식점들만 가져오는 것은 어려울 것 같습니다. 다만 크롤링을 해올 때 해당 위치에서 가까운 거리 순으로 데이터를 가져올 수는 있을 것 같아요.
