### ISSUE TITLE
selenium.py파일 오류

### ISSUE THREAD

**Issue by kimtaewan22** [parkss404/Serp1ck#60]
해당 파일을 vs code로 실행했을 때 ctrl F5로 실행을 한다면 제대로 작동을 하지 않습니다. 대신 파일 실행을 하면 정상적으로 작동이 되니 참고 바랍니다.

**Comment by KGE108** [comment]
참고하겠습니다.

**Comment by kimtaewan22** [comment]
네 추가적인 오류가 있다면 다시 공지하겠습니다.
