### ISSUE TITLE
챗봇 음식 다시 받기

### ISSUE THREAD

**Issue by kimtaewan22** [parkss404/Serp1ck#62]
챗봇에서 음식이 원하는 것이 나오지 않았다면 처음부터 다시 받을 수 있도록 하는 건 어떨까요?

**Comment by KGE108** [comment]
다시 받아도 마음에 드는 음식이 없다면 다시 처음부터 가는 것도 좋을 것 같습니다.

**Comment by kimtaewan22** [comment]
해당 기능을 추가해서 구현하도록 해야겠네요
