### ISSUE TITLE
대학 인근 맛집정보 수집방법

### ISSUE THREAD

**Issue by parkss404** [parkss404/Serp1ck#7]
맛집은 어떤 방식,기준으로 수집해야 할까요?

**Comment by kimtaewan22** [comment]
리뷰수나 별점을 기준으로 수집하는 것이 좋을 것 같습니다.

**Comment by KGE108** [comment]
학생들에게서 맛집정보를 받는 것도 좋을 것 같습니다.

**Comment by parkss404** [comment]
그러면 에브리타임이나 지인들을 통해 맛집추천을 받아보도록 하죠
