### ISSUE TITLE
에브리타임을 이용한 자료조사 방법

### ISSUE THREAD

**Issue by KGE108** [parkss404/Serp1ck#8]

**Comment by KGE108** [comment]
에브리타임에 있던 기존 자료들을 사용할까요? 새로운 자료를 받을까요?

**Comment by kimtaewan22** [comment]
기존 자료에다가 플러스로 새로운 자료를 받아서 같이 활용하는 것이 좋을 것 같습니다.

**Comment by KGE108** [comment]
그렇다면 설문조사를 통해 학생들에게 가게를 추천 받는 걸로 해봅시다.
