### ISSUE TITLE
클릭 에러

### ISSUE THREAD

**Issue by kimtaewan22** [parkss404/Serp1ck#9]
현재 번호를 받아서 위치를 입력 받고 크롤링을 해올 때 클릭이 되지 않는 에러가 발생하고 있습니다.

**Comment by parkss404** [comment]
셀레니움으로 크롬에서 실행 했을 때 클릭이 안된다는 건가요??

**Comment by kimtaewan22** [comment]
맞습니다 검색 버튼을 클릭해야되는데 클릭이 안 되는 오류가 발생하고 있습니다.

**Comment by kimtaewan22** [comment]
요소를 찾을 때 xpath가 아닌 css_selector를 이용하니까 해당 문제가 해결됐습니다.
